# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHSsEqpMgLkMiO5a-xXgOvs-j3YpA6tM
"""

import sys
from textblob import TextBlob

def analyze_sentiment(text):
    """Analyze sentiment of the input text using TextBlob."""
    blob = TextBlob(text)
    sentiment = blob.sentiment
    return sentiment.polarity, sentiment.subjectivity

def main():
    if len(sys.argv) != 2:
        print("Usage: python sentiment_analysis.py 'Your text here'")
        sys.exit(1)

    text = sys.argv[1]
    polarity, subjectivity = analyze_sentiment(text)

    print(f"Text: {text}")
    print(f"Polarity: {polarity:.2f}")
    print(f"Subjectivity: {subjectivity:.2f}")

    if polarity > 0:
        print("The sentiment of the text is positive.")
    elif polarity < 0:
        print("The sentiment of the text is negative.")
    else:
        print("The sentiment of the text is neutral.")

if __name__ == "__main__":
    main()